# @package _group_

common:
  fp16: true
  log_format: simple
  log_interval: 200

checkpoint:
  save_interval_updates: 25000
  keep_interval_updates: 1
  #no_epoch_checkpoints: true

task:
  _name: audio_pretraining2
  data: ???
  train_data: train_960
  dev_data: dev_clean
  max_sample_size: 3000
  min_sample_size: 150
  low_frame_rate: true

dataset:
  num_workers: 6
  max_tokens: 35000
  skip_invalid_size_inputs_valid_test: true

distributed_training:
  ddp_backend: legacy_ddp
  distributed_world_size: 8

criterion:
  _name: decoar
  infonce: true
  log_keys: ["prob_perplexity","code_perplexity", "temp"]

optimization:
  max_update: 800000
  lr: [0.0001]

optimizer:
  _name: adam
  adam_betas: (0.9,0.98)
  adam_eps: 1e-06
  weight_decay: 0.01

lr_scheduler:
  _name: polynomial_decay
  warmup_updates: 64000

model:
  _name: decoar2b
  quant_path: /home/ubuntu/efs/users/shaosl/decoar2/fairseq/outputs/2021-05-31/19-43-01/checkpoints/checkpoint_best.pt
  dropout_input: 0.1
  dropout_features: 0.1
  encoder_embed_dim: 768
  encoder_layerdrop: 0.05
  mask_prob: 0.09
  no_mask_overlap: true
  latent_vars: 512
  latent_groups: 1
  latent_temp: [1, 1, 1]