# @package _group_

common:
  fp16: true
  log_format: simple
  log_interval: 200

checkpoint:
  save_interval_updates: 25000
  keep_interval_updates: 1
  no_epoch_checkpoints: true

task:
  _name: audio_pretraining2
  data: ???
  train_data: train_960
  dev_data: dev_clean
  max_sample_size: 3000
  min_sample_size: 150
  low_frame_rate: true

dataset:
  num_workers: 6
  max_tokens: 80000
  skip_invalid_size_inputs_valid_test: true

distributed_training:
  ddp_backend: legacy_ddp
  distributed_world_size: 8

criterion:
  _name: decoar
  infonce: false

optimization:
  max_update: 10000
  lr: [0.001]

optimizer:
  _name: adam
  adam_betas: (0.9,0.98)
  adam_eps: 1e-06
  weight_decay: 0.01

lr_scheduler:
  _name: polynomial_decay
  warmup_updates: 100

model:
  _name: quant
  latent_vars: 1024