# @package _group_

common:
  fp16: true
  log_format: simple
  log_interval: 100

checkpoint:
  save_interval: 50
  save_interval_updates: 1000
  keep_interval_updates: 1
  no_epoch_checkpoints: true
  best_checkpoint_metric: wer

task:
  _name: audio_pretraining2
  train_data: train_10h
  dev_data: dev_clean
  data: ???
  labels: ltr
  enable_padding: true
  max_sample_size: 3000
  min_sample_size: 150
  low_frame_rate: true
  #down_sample_rate: 3

dataset:
  num_workers: 6
  max_tokens: 80000
  validate_after_updates: 800
  validate_interval: 20
  skip_invalid_size_inputs_valid_test: true

distributed_training:
  ddp_backend: legacy_ddp
  distributed_world_size: 1

criterion:
  _name: ctc
  zero_infinity: true

optimization:
  max_update: 10000
  lr: [0.0005]
  sentence_avg: true
  update_freq: [2]

optimizer:
  _name: adam
  adam_betas: (0.9,0.98)
  adam_eps: 1e-08

lr_scheduler:
  _name: polynomial_decay
  warmup_updates: 800

model:
  _name: wav2vec_ctc
  w2v_path: /home/ubuntu/efs/users/shaosl/decoar2/fairseq/outputs/2021-06-13/22-57-33/checkpoints/checkpoint_last.pt
  apply_mask: true
  mask_prob: 0.5
  #mask_length: 7
  mask_channel_prob: 0.5
  mask_channel_length: 64
  freeze_finetune_updates: 50000

